acme:
  enabled: true
  remote-address: 192.168.0.108
  security:
    username: txjava
    password: 123
    roles:
      - 男主角
      - 摄影师
      - 女主角
  my-person:
    person:
      first-name: 亮哥
      age: 30
      email: aaaa
      school:
        sname: txjava
  favor: 篮球, 足球, 铅球

