server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment


eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进 EurekaServer 默认为true
    fetch-registry: true # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机版
      #d efaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
