server:
  port: 80

eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册进 EurekaServer 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
# 用于服务降级，在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true # 在Feign中开启Hystrix
